import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Member} from '../src/composants/Member/Member'
import {Header} from '../src/composants/Header/Header'
import {SideBar} from '../src/composants/SideBar/SideBar'

export default function Home() {
    
    var MemberAiroleChef=[{
        name:'Barret', image:'/images/Membre/Barret.jpg'}
      ]

      var MemberAiroleBrasDroit=[{
        name:'HAM3NK', image:'/images/Membre/Ham3nk.jpg'}
      ]

      var MemberAiroleCapitaine=[{
        name:'Gnano', image:'/images/unnamed.jpg'}
      ]

      var MemberAirole=[{
        name:'Flothia', image:'/images/unnamed.jpg'},{
        name:'Onlzebu', image:'/images/unnamed.jpg'},{
        name:'Seramon', image:'/images/unnamed.jpg'},{
        name:'sethart', image:'/images/unnamed.jpg'},{
        name:'Rinuc', image:'/images/unnamed.jpg'},{
        name:'Bolmog', image:'/images/unnamed.jpg'},{
        name:'Ahzam', image:'/images/unnamed.jpg'},{
        name:'Luck', image:'/images/unnamed.jpg'},{
        name:'Loupi', image:'/images/unnamed.jpg'},{
        name:'Hanryu', image:'/images/unnamed.jpg'},{
        name:'Briareos', image:'/images/unnamed.jpg'},{
        name:'Storm2', image:'/images/unnamed.jpg'},{
        name:'Bighood', image:'/images/unnamed.jpg'},{
        name:'Caim', image:'/images/unnamed.jpg'}
      ]

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <SideBar/>

      <div className={styles.guildeAiroleContainer}>
        <h2>Airole</h2>
        <h3>Chef</h3>
        <div className={styles.guildeAiroleChefContainer}>
          {MemberAiroleChef.map((member, index) => (<Member name={member.name} key={index} image={member.image}/>))}
        </div>

        <h3>Bras Droit</h3>
        <div className={styles.guildeAiroleBrasDroitContainer}>
          {MemberAiroleBrasDroit.map((member, index) => (<Member name={member.name} key={index} image={member.image}/>))}
        </div>
        
        <h3>Capitaine</h3>
        <div className={styles.guildeAiroleCapitaineContainer}>
          {MemberAiroleCapitaine.map((member, index) => (<Member name={member.name} key={index} image={member.image}/>))}
        </div>

        <h3>Membre</h3>
        <div className={styles.guildeAiroleMemberContainer}>
          {MemberAirole.map((member, index) => (<Member name={member.name} key={index} image={member.image}/>))}
        </div>
      
      </div>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
