import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Unite} from '../src/composants/Unite/Unite'
import {Element} from '../src/composants/Unite/Element'
import {Chimere} from '../src/composants/Chimere/Chimere'
import {Header} from '../src/composants/Header/Header'
import {SideBar} from '../src/composants/SideBar/SideBar'
import {AV} from '../src/composants/AV/AV'
import { useState, useEffect } from 'react'
const axios = require('axios');

export default function Home() {
    const [unitesEarthUR, setUnitesEarthUR] = useState([]);
    useEffect(() =>{
        test()
    }, [])

    const [unitesEarthMR, setUnitesEarthMR] = useState([]);
    useEffect(() =>{
        test2()
    }, [])
    
    //   var unitesMREarth=[{
    //     name:'Dorando', element:'earth', sniv:'/niv:', niv:99, image:'/images/Unite/MR/Dorando.png'},{
    //     name:'éthéa', element:'earth', sniv:'/niv:', niv:0, image:'/images/Unite/MR/éthéa.png'},{
    //     name:'Liviale', element:'earth', sniv:'/niv:', niv:120, image:'/images/Unite/MR/Liviale.png'},{
    //     name:'Lorenzo', element:'earth', sniv:'/niv:', niv:0, image:'/images/Unite/MR/Lorenzo.png'},{
    //     name:'Mont Leonis', element:'earth', sniv:'/niv:', niv:0, image:'/images/Unite/MR/Mont Leonis.png'},{
    //     name:'Mustadio', element:'earth', sniv:'/niv:', niv:0, image:'/images/Unite/MR/Mustadio.png'}
    //   ]

      var unitesSREarth=[{
        name:'Murmure', element:'earth', sniv:'/niv:', niv:99, image:'/images/Unite/SR/Murmure.png'},{
        name:'Beilo', element:'earth', sniv:'/niv:', niv:0, image:'/images/Unite/SR/Beilo.png'}
      ]

      var atvUREarth=[{
        name:'Caelum', elem:'earth', image:'/images/AV/Caelum.png'},{
        name:'Coeur insondable', elem:'earth', image:'/images/AV/Coeur insondable.png'},{
        name:'Golem', elem:'earth', image:'/images/AV/Golem.png'},{
        name:'Héros le temps dun rêve', elem:'earth', image:'/images/AV/Héros le temps dun rêve.png'},{
        name:'Hurlement résonnant', elem:'earth', image:'/images/AV/Hurlement résonnant.png'},{
        name:'Le lion solitaire', elem:'earth', image:'/images/AV/Le lion solitaire.png'},{
        name:'Titan', elem:'earth', image:'/images/AV/Titan.png'}
      ]
  
      var atvMREarth=[{
        name:'Admiratrices rivales', elem:'earth', image:'/images/AV/MR/Admiratrices rivales.png'},{
        name:'Ordres confidentiels', elem:'earth', image:'/images/AV/MR/Ordres confidentiels.png'},{
        name:'Otyugh', elem:'earth', image:'/images/AV/MR/Otyugh.png'},{
        name:'Par-delà les terres', elem:'earth', image:'/images/AV/MR/Par-delà les terres.png'},{
        name:'Pommes du souvenir', elem:'earth', image:'/images/AV/MR/Pommes du souvenir.png'},{
        name:'Une année daventures', elem:'earth', image:'/images/AV/MR/Une année daventures.png'}
      ]

      var chimereUREarth=[{
        name:'Golem', elem:'earth', image:'/images/Chimère/Golem.png'},{
        name:'Titan', elem:'earth', image:'/images/Chimère/Titan.png'}
        ]

        var chimereMREarth=[{
        name:'Otyugh', elem:'earth', image:'/images/Chimère/Otyugh.png'}
        ]
        
      var chimereSREarth=[{
        name:'Pampa', elem:'earth', image:'/images/Chimère/Pampa.png'}
        ]

    const test = async () => {
        let response = await axios.get('http://localhost:8080/api/Unites/Earth/UR');
        setUnitesEarthUR(response.data);
    }

    const test2 = async () => {
        let response = await axios.get('http://localhost:8080/api/Unites/Earth/MR');
        setUnitesEarthMR(response.data);
    }
    
      return (

        <div className={styles.container}>
            <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header/>
            <SideBar/>

            <div className={styles.uniteContainer}>
            <h4>Earth UR</h4>
            <Element elem='earth' name='earth' ></Element>
            <h5>Unités UR</h5>
                
                <div className={styles.elemEarthContainer}>
                {unitesEarthUR.map((unite, index) => (<Unite name={unite.name} element={unite.element} sniv={unite.sniv} niv={unite.niv} key={index} image={unite.image}/>))}
                </div>
            <h5>Atout vision UR</h5>
                <div className={styles.AV2}>
                    {atvUREarth.map((av, index) => (<AV name={av.name} element={av.elem} key={index} image={av.image}/>))}
                </div>
            <h5>Chimère UR</h5>
                <div className={styles.chimere}>
                    {chimereUREarth.map((chimere, index) => (<Chimere name={chimere.name} element={chimere.elem} key={index} image={chimere.image}/>))}
                </div>
            <h4>Earth MR</h4>
            <h5>Unités MR</h5>
                <div className={styles.elemEarthContainer}>
                {unitesEarthMR.map((unite, index) => (<Unite name={unite.name} element={unite.element} sniv={unite.sniv} niv={unite.niv} key={index} image={unite.image}/>))}
                </div>
            <h5>Atout vision MR</h5>
                <div className={styles.AV2}>
                    {atvMREarth.map((av, index) => (<AV name={av.name} element={av.elem} key={index} image={av.image}/>))}
                </div>
            <h5>Chimère MR</h5>
                <div className={styles.chimere}>
                    {chimereMREarth.map((chimere, index) => (<Chimere name={chimere.name} element={chimere.elem} key={index} image={chimere.image}/>))}
                </div>
            <h4>Earth SR</h4>
                <div className={styles.elemEarthContainer}>
                {unitesSREarth.map((unite, index) => (<Unite name={unite.name} element={unite.element} sniv={unite.sniv} niv={unite.niv} key={index} image={unite.image}/>))}
                </div>
                <div className={styles.chimere}>
                    {chimereSREarth.map((chimere, index) => (<Chimere name={chimere.name} element={chimere.elem} key={index} image={chimere.image}/>))}
                </div>
            </div>
        </div>
    )
}