import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Unite} from '../src/composants/Unite/Unite'
import {Element} from '../src/composants/Unite/Element'
import {Chimere} from '../src/composants/Chimere/Chimere'
import {Header} from '../src/composants/Header/Header'
import {SideBar} from '../src/composants/SideBar/SideBar'
import {AV} from '../src/composants/AV/AV'
import { useState, useEffect } from 'react'
const axios = require('axios');

export default function Home() {
    const [unitesiceUR, setUnitesiceUR] = useState([]);
    useEffect(() =>{
        test()
    }, [])

    const [unitesiceMR, setUnitesiceMR] = useState([]);
    useEffect(() =>{
        test2()
    }, [])

    // var unitesURIce=[{
    // name:'Agrias',  element:'ice', sniv:'/niv:', niv:0, image:'/images/Unite/Agrias.png'},{
    // name:'Auron',  element:'ice', sniv:'/niv:', niv:0, image:'/images/Unite/Auron.png'},{
    // name:'Fryevia',  element:'ice', sniv:'/niv:', niv:0, image:'/images/Unite/Fryevia.png'},{
    // name:'Gilgamesh',  element:'ice', sniv:'/niv:', niv:0, image:'/images/Unite/Gilgamesh.png'},{
    // name:'Laswell',  element:'ice', sniv:'/niv:', niv:0, image:'/images/Unite/Laswell.png'},{
    // name:'Mediena',  element:'ice', sniv:'/niv:', niv:0, image:'/images/Unite/Mediena.png'},{
    // name:'Rosa',  element:'ice', sniv:'/niv:', niv:0, image:'/images/Unite/Rosa.png'},{
    // name:'Saliah Romantique',  element:'ice', sniv:'/niv:', niv:0, image:'/images/Unite/Saliah Romantique.png'},{
    // name:'Viktora',  element:'ice', sniv:'/niv:', niv:0,  image:'/images/Unite/Viktora.png'}
    // ]
    // var unitesMRIce=[{
    // name:'Chel', element:'ice', sniv:'/niv:', niv:99, image:'/images/Unite/MR/Chel.png'},{
    // name:'Khory Wezett', element:'ice', sniv:'/niv:', niv:0, image:'/images/Unite/MR/Khory Wezett.png'},{
    // name:'Nasha', element:'ice', sniv:'/niv:', niv:120, image:'/images/Unite/MR/Nasha.png'}
    // ]
    var unitesSRIce=[{
    name:'Serjes', element:'ice', sniv:'/niv:', niv:99, image:'/images/Unite/SR/Serjes.png'},{
    name:'Valaïde', element:'ice', sniv:'/niv:', niv:0, image:'/images/Unite/SR/Valaïde.png'}
    ]

    var atvURIce=[{
        name:'Fenrir', elem:'ice', image:'/images/AV/Fenrir.png'},{
        name:'Freezus', elem:'ice', image:'/images/AV/Freezus.png'},{
        name:'Masque de la perfidie', elem:'ice', image:'/images/AV/Masque de la perfidie.png'},{
        name:'Odin', elem:'ice', image:'/images/AV/Odin.png'},{
        name:'Shiva', elem:'ice', image:'/images/AV/Shiva.png'}
      ]
  
      var atvMRIce=[{
        name:'Concentration optimale', elem:'ice', image:'/images/AV/MR/Concentration optimale.png'},{
        name:'Glacial', elem:'ice', image:'/images/AV/MR/Glacial.png'},{
        name:'Les quatre seigneurs de guerre', elem:'ice', image:'/images/AV/MR/Les quatre seigneurs de guerre.png'},{
        name:'Mog de la nuit hivernale', elem:'ice', image:'/images/AV/MR/Mog de la nuit hivernale.png'},{
        name:'Un adversaire imbattable', elem:'ice', image:'/images/AV/MR/Un adversaire imbattable.png'}
      ]

    var chimereURIce=[{
    name:'Fenrir', elem:'ice', image:'/images/Chimère/Fenrir.png'},{
    name:'Shiva', elem:'ice', image:'/images/Chimère/Shiva.png'}
    ]

var chimereMRIce=[{
    name:'Glacial', elem:'ice', image:'/images/Chimère/Glacial.png'},{
    name:'Mog hiver', elem:'ice', image:'/images/Chimère/Mog hiver.png'}
    ]

    var chimereSRIce=[{
    name:'Oeil flottant', elem:'ice', image:'/images/Chimère/Oeil flottant.png'}
    ]

    const test = async () => {
        let response = await axios.get('http://localhost:8080/api/Unites/ice/UR');
        setUnitesiceUR(response.data);
    }
    const test2 = async () => {
        let response = await axios.get('http://localhost:8080/api/Unites/ice/MR');
        setUnitesiceMR(response.data);
    }



      return (

        <div className={styles.container}>
            <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header/>
            <SideBar/>

            <div className={styles.uniteContainer}>
            <h4>Ice UR</h4>
            <Element elem='ice' name='ice' ></Element>
            <h5>Unités UR</h5>
                
                <div className={styles.elemIceContainer}>
                {unitesiceUR.map((unite, index) => (<Unite name={unite.name} element={unite.element} sniv={unite.sniv} niv={unite.niv} key={index} image={unite.image}/>))}
                </div>
            <h5>Atout vision UR</h5>
                <div className={styles.AV2}>
                    {atvURIce.map((av, index) => (<AV name={av.name} element={av.elem} key={index} image={av.image}/>))}
                </div>
            <h5>Chimère UR</h5>
                <div className={styles.chimere}>
                    {chimereURIce.map((chimere, index) => (<Chimere name={chimere.name} element={chimere.elem} key={index} image={chimere.image}/>))}
                </div>
            <h4>Ice MR</h4>
            <h5>Unités MR</h5>
                <div className={styles.elemIceContainer}>
                {unitesiceMR.map((unite, index) => (<Unite name={unite.name} element={unite.element} sniv={unite.sniv} niv={unite.niv} key={index} image={unite.image}/>))}
                </div>
            <h5>Atout vision MR</h5>
                <div className={styles.AV2}>
                    {atvMRIce.map((av, index) => (<AV name={av.name} element={av.elem} key={index} image={av.image}/>))}
                </div>
            <h5>Chimère MR</h5>
                <div className={styles.chimere}>
                    {chimereMRIce.map((chimere, index) => (<Chimere name={chimere.name} element={chimere.elem} key={index} image={chimere.image}/>))}
                </div>
            <h4>Ice SR</h4>
                <div className={styles.elemIceContainer}>
                {unitesSRIce.map((unite, index) => (<Unite name={unite.name} element={unite.element} sniv={unite.sniv} niv={unite.niv} key={index} image={unite.image}/>))}
                </div>
                <div className={styles.chimere}>
                    {chimereSRIce.map((chimere, index) => (<Chimere name={chimere.name} element={chimere.elem} key={index} image={chimere.image}/>))}
                </div>

            </div>
        </div>
    )
}