import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Member} from '../src/composants/Member/Member'
import {Header} from '../src/composants/Header/Header'
import {SideBar} from '../src/composants/SideBar/SideBar'


export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <SideBar/>


      
      
      
      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
