import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Login} from '../src/composants/Login/Login'
import { useRouter } from 'next/router'
import {useEffect} from 'react'

export default function Home() {

  const router = useRouter()
  const OnElementClick = (route: string) => {
      router.push(`/${route}`)
    }

useEffect(() => {
  let session = localStorage.getItem('session')
  if(session !=null) {
  session = JSON.parse(session)
  router.push('Main')
}
}, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
    <div className={styles.form}>
    <Login/>
  
  <button className={styles.ButtonEloria} onClick={() => {OnElementClick('Inscription')}}>Inscription</button>

  </div>
      
      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
