import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Inscription} from '../src/composants/Inscription/Inscription'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <div className={styles.inscription}>
    <Inscription/>
    
  </div>
      
      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
