import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Member} from '../src/composants/Member/Member'
import {Header} from '../src/composants/Header/Header'
import {SideBar} from '../src/composants/SideBar/SideBar'

export default function Home() {
    
    var MemberEloriachef=[{
      name:'Demed', image:'/images/Membre/Demed.png'}
    ]

    var MemberEloriaBrasDroit=[{
      name:'Kiba', image:'/images/Membre/Kiba.png'},{
      name:'Razmo', image:'/images/Membre/Razmo.jpg'},{
      name:'Schlagen', image:'/images/Membre/Schlagen.jpg'},{
      name:'Oscar', image:'/images/unnamed.jpg'},{
      name:'Link', image:'/images/Membre/Link.jpg'},{
      name:'Unknown', image:'/images/Membre/Unknown.jpg'}
    ]

    var MemberEloriaCapitaine=[{
      name:'typher', image:'/images/unnamed.jpg'},{
      name:'Zhak', image:'/images/unnamed.jpg'},{
      name:'FarAlex', image:'/images/Membre/FarAlex.png'},{
      name:'Perlin', image:'/images/Membre/Perlin.png'},{
      name:'Flo408', image:'/images/Membre/Flo.png'},{
      name:'Djinsung', image:'/images/Membre/Djinsung.png'}
    ]

    var MemberEloria=[{
      name:'Angenoir', image:'/images/unnamed.jpg'},{
      name:'Samba93', image:'/images/unnamed.jpg'},{
      name:'Wrath', image:'/images/unnamed.jpg'},{
      name:'sethart', image:'/images/unnamed.jpg'},{
      name:'SamZR', image:'/images/unnamed.jpg'},{
      name:'Bahamut', image:'/images/unnamed.jpg'},{
      name:'Pype', image:'/images/unnamed.jpg'},{
      name:'Vexxy', image:'/images/unnamed.jpg'},{
      name:'Tamouna22', image:'/images/unnamed.jpg'},{
      name:'Miseru', image:'/images/unnamed.jpg'},{
      name:'Grandcoeur', image:'/images/unnamed.jpg'},{
      name:'Pikajon', image:'/images/unnamed.jpg'},{
      name:'Lloyd', image:'/images/unnamed.jpg'},{
      name:'Gina', image:'/images/unnamed.jpg'},{
      name:'Garzeth', image:'/images/unnamed.jpg'},{
      name:'Sherda', image:'/images/unnamed.jpg'},{
      name:'Keille', image:'/images/unnamed.jpg'}
    ]
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <SideBar/>

      <h2>Ivalice</h2>
      <Member name='Xya' image='/images/unnamed.jpg'></Member>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
