import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Unite} from '../src/composants/Unite/Unite'
import {Element} from '../src/composants/Unite/Element'
import {Chimere} from '../src/composants/Chimere/Chimere'
import {Header} from '../src/composants/Header/Header'
import {SideBar} from '../src/composants/SideBar/SideBar'
import {AV} from '../src/composants/AV/AV'

export default function Home() {
    var unitesURLightning=[{
        name:'9S', element:'lightning', sniv:'/niv:', niv:0, image:'/images/Unite/9S.png'},{
        name:'Frederika', element:'lightning', sniv:'/niv:', niv:0, image:'/images/Unite/Frederika.png'},{
        name:'NivLu', element:'lightning', sniv:'/niv:', niv:0, image:'/images/Unite/NivLu.png'},{
        name:'Orlandeau', element:'lightning', sniv:'/niv:', niv:0, image:'/images/Unite/Orlandeau.png'},{
        name:'Skahal', element:'lightning', sniv:'/niv:', niv:0, image:'/images/Unite/Skahal.png'}
      ]
      var unitesMRLightning=[{
        name:'Alym', element:'lightning', sniv:'/niv:', niv:99, image:'/images/Unite/MR/Alym.png'},{
        name:'Marie-luke', element:'lightning', sniv:'/niv:', niv:0, image:'/images/Unite/MR/Marie-luke.png'},{
        name:'Owe', element:'lightning', sniv:'/niv:', niv:120, image:'/images/Unite/MR/Owe.png'},{
        name:'Raviesse', element:'lightning', sniv:'/niv:', niv:0, image:'/images/Unite/MR/Raviesse.png'},{
        name:'Saliah', element:'lightning', sniv:'/niv:', niv:0, image:'/images/Unite/MR/Saliah.png'},{
        name:'Schuzelt', element:'lightning', sniv:'/niv:', niv:0, image:'/images/Unite/MR/Schuzelt.png'},{
        name:'Sylma', element:'lightning', sniv:'/niv:', niv:0, image:'/images/Unite/MR/Sylma.png'}
      ]
      var unitesSRLightning=[{
        name:'Vadim', element:'lightning', sniv:'/niv:', niv:99, image:'/images/Unite/SR/Vadim.png'}
      ]
      var unitesRLightning=[{
        name:'Learte', element:'lightning', sniv:'/niv:', niv:99, image:'/images/Unite/R/Learte.png'}
      ]

      var atvURLightning=[{
        name:'éclosion dans la nuit noire', elem:'lightning', image:'/images/AV/éclosion dans la nuit noire.png'},{
        name:'égéon', elem:'lightning', image:'/images/AV/égéon.png'},{
        name:'Ramuh', elem:'lightning', image:'/images/AV/Ramuh.png'},{
        name:'Rêve de Frederika', elem:'lightning', image:'/images/AV/Rêve de Frederika.png'}
      ]
  
      var atvMRLightning=[{
        name:'Rubeus', elem:'earth', image:'/images/AV/MR/Rubeus.png'},{
        name:'Coeurl', elem:'earth', image:'/images/AV/MR/Coeurl.png'},{
        name:'Déclaration damour', elem:'earth', image:'/images/AV/MR/Déclaration damour.png'},{
        name:'La magicienne jalouse', elem:'earth', image:'/images/AV/MR/La magicienne jalouse.png'},{
        name:'Tomberry', elem:'earth', image:'/images/AV/MR/Tomberry.png'},{
        name:'Voix de lépéiste raffiné', elem:'earth', image:'/images/AV/MR/Voix de lépéiste raffiné.png'}
      ]

    var chimereURLightning=[{
        name:'Egéon', elem:'lightning', image:'/images/Chimère/Egéon.png'},{
        name:'Ramuh', elem:'lightning', image:'/images/Chimère/Ramuh.png'}
        ]

    var chimereMRLightning=[{
        name:'Coeurl', elem:'lightning', image:'/images/Chimère/Freezus.png'},{
        name:'Tomberry', elem:'lightning', image:'/images/Chimère/Tomberry.png'}
        ]

    var chimereSRLightning=[{
        name:'Ogre', elem:'lightning', image:'/images/Chimère/Ogre.png'}
        ]

  
      return (

        <div className={styles.container}>
            <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header/>
            <SideBar/>

            <div className={styles.uniteContainer}>
            <h4>Lightning UR</h4>
            <Element elem='lightning' name='lightning' ></Element>
            <h5>Unités UR</h5>
                
                <div className={styles.elemLightningContainer}>
                {unitesURLightning.map((unite, index) => (<Unite name={unite.name} element={unite.element} sniv={unite.sniv} niv={unite.niv} key={index} image={unite.image}/>))}
                </div>
            <h5>Atout vision UR</h5>
                <div className={styles.AV2}>
                    {atvURLightning.map((av, index) => (<AV name={av.name} element={av.elem} key={index} image={av.image}/>))}
                </div>
            <h5>Chimère UR</h5>
                <div className={styles.chimere}>
                    {chimereURLightning.map((chimere, index) => (<Chimere name={chimere.name} element={chimere.elem} key={index} image={chimere.image}/>))}
                </div>
            <h4>Lightning MR</h4>
            <h5>Unités MR</h5>
                <div className={styles.elemLightningContainer}>
                {unitesMRLightning.map((unite, index) => (<Unite name={unite.name} element={unite.element} sniv={unite.sniv} niv={unite.niv} key={index} image={unite.image}/>))}
                </div>
            <h5>Atout vision MR</h5>
                <div className={styles.AV2}>
                    {atvMRLightning.map((av, index) => (<AV name={av.name} element={av.elem} key={index} image={av.image}/>))}
                </div>
            <h5>Chimère MR</h5>
                <div className={styles.chimere}>
                    {chimereMRLightning.map((chimere, index) => (<Chimere name={chimere.name} element={chimere.elem} key={index} image={chimere.image}/>))}
                </div>
            <h4>Lightning SR</h4>
                <div className={styles.elemLightningContainer}>
                {unitesSRLightning.map((unite, index) => (<Unite name={unite.name} element={unite.element} sniv={unite.sniv} niv={unite.niv} key={index} image={unite.image}/>))}
                </div>
                <div className={styles.chimere}>
                    {chimereSRLightning.map((chimere, index) => (<Chimere name={chimere.name} element={chimere.elem} key={index} image={chimere.image}/>))}
                </div>
            <h4>Lightning R</h4>
                <div className={styles.elemLightningContainer}>
                {unitesRLightning.map((unite, index) => (<Unite name={unite.name} element={unite.element} sniv={unite.sniv} niv={unite.niv} key={index} image={unite.image}/>))}
                </div>
            </div>
        </div>
    )
}