import Head from 'next/head'
import styles from '../src/composants/Equipement/Equipement.module.css'
import {Header} from '../src/composants/Header/Header'
import {SideBar} from '../src/composants/SideBar/SideBar'
import {Equipement} from '../src/composants/Equipement/Equipement'
import { useRouter } from 'next/router'


export default function Home() {
    const router = useRouter()
    const OnElementClick = (route:string) => {
        router.push(`/${route}`)
      }

var SwordUR=[{
    name:'épée de service de la garde royale de Lesalia', image:'/images/Equipement/Arme/Sword/épée de service de la garde royale de Lesalia.png'},{
    name:'Excalibur', image:'/images/Equipement/Arme/Sword/Excalibur.png'
}]
var SwordMR=[{
    name:'Araignée dansante', image:'/images/Equipement/Arme/Sword/Araignée dansante.png'},{
    name:'Cryolame', image:'/images/Equipement/Arme/Sword/Cryolame.png'},{
    name:'épée dEhwaz', image:'/images/Equipement/Arme/Sword/épée dEhwaz.png'},{
    name:'épée de corail', image:'/images/Equipement/Arme/Sword/épée de corail.png'},{
    name:'épée de lumière', image:'/images/Equipement/Arme/Sword/épée de lumière.png'},{
    name:'épée enflammée', image:'/images/Equipement/Arme/Sword/épée enflammée.png'},{
    name:'épée vertébrale', image:'/images/Equipement/Arme/Sword/épée vertébrale.png'},{
    name:'épée vermillon', image:'/images/Equipement/Arme/Sword/épée vermillon.png'},{
    name:'Fraternité', image:'/images/Equipement/Arme/Sword/Fraternité.png'},{
    name:'Lame de feu', image:'/images/Equipement/Arme/Sword/Lame de feu.png'},{
    name:'Lame guide', image:'/images/Equipement/Arme/Sword/Lame guide.png'},{
    name:'Lame Morphée', image:'/images/Equipement/Arme/Sword/Lame Morphée.png'},{
    name:'Lohengrin', image:'/images/Equipement/Arme/Sword/Lohengrin.png'},{
    name:'Nagrarok', image:'/images/Equipement/Arme/Sword/Nagrarok.png'},{
    name:'Pyrolame', image:'/images/Equipement/Arme/Sword/Pyrolame.png'},{
    name:'Rapière pourpre', image:'/images/Equipement/Arme/Sword/Rapière pourpre.png'},{
    name:'Réplique de Coeur-de-lion', image:'/images/Equipement/Arme/Sword/Réplique de Coeur-de-lion.png'},{
    name:'Servante insignifiante', image:'/images/Equipement/Arme/Sword/Lame guide.png'},{
    name:'Vermillon', image:'/images/Equipement/Arme/Sword/Vermillon.png'}
    
]
var SwordSR=[{
    name:'Brise métal', image:'/images/Equipement/Arme/Sword/Brise métal.png'},{
    name:'épée en mithril', image:'/images/Equipement/Arme/Sword/épée en mithril.png'
}]
var SwordR=[{
    name:'épée longue', image:'/images/Equipement/Arme/Sword/épée longue.png'
}]
var SwordN=[{
    name:'épée large', image:'/images/Equipement/Arme/Sword/épée large.png'
}]

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <SideBar/>


        <div className={styles.equipementContainer}>
            <h3>Arme</h3>
            <button className={styles.ButtonAxe} onClick={() => {OnElementClick('Axe')}}>Axe</button>
            <button className={styles.ButtonBook} onClick={() => {OnElementClick('Book')}}>Book</button>
            <button className={styles.ButtonBow} onClick={() => {OnElementClick('Bow')}}>Bow</button>
            <button className={styles.ButtonDagger} onClick={() => {OnElementClick('Dagger')}}>Dagger</button>
            <button className={styles.ButtonFist} onClick={() => {OnElementClick('Fist')}}>Fist</button>
            <button className={styles.ButtonGlove} onClick={() => {OnElementClick('Glove')}}>Glove</button>
            <button className={styles.ButtonGreatSword} onClick={() => {OnElementClick('GreatSword')}}>GreatSword</button>
            <button className={styles.ButtonGun} onClick={() => {OnElementClick('Gun')}}>Gun</button>
            <button className={styles.ButtonKatana} onClick={() => {OnElementClick('Katana')}}>Katana</button>
            <button className={styles.ButtonMace} onClick={() => {OnElementClick('Mace')}}>Mace</button>
            <button className={styles.ButtonNinjaBlade} onClick={() => {OnElementClick('NinjaBlade')}}>NinjaBlade</button>
            <button className={styles.ButtonRod} onClick={() => {OnElementClick('Rod')}}>Rod</button>
            <button className={styles.ButtonSpear} onClick={() => {OnElementClick('Spear')}}>Spear</button>
            <button className={styles.ButtonSword} onClick={() => {OnElementClick('Sword')}}>Sword</button>

            <h3>Armor</h3>
            <button className={styles.ButtonArmor} onClick={() => {OnElementClick('Armor')}}>Armor</button>
            <button className={styles.ButtonCloth} onClick={() => {OnElementClick('Cloth')}}>Cloth</button>
            <button className={styles.ButtonHat} onClick={() => {OnElementClick('Hat')}}>Hat</button>
            <button className={styles.ButtonHelm} onClick={() => {OnElementClick('Helm')}}>Helm</button>
            <button className={styles.ButtonShield} onClick={() => {OnElementClick('Shield')}}>Shield</button>

            <h3>Accessory</h3>
            <button className={styles.ButtonAccessory} onClick={() => {OnElementClick('Accessory')}}>Accessory</button>

        </div>




        <div className={styles.equipementContainer}>


            <h3>Sword</h3>
            <h4>UR</h4>
            <div className={styles.equipement}>
                {SwordUR.map((equipement, index) => (<Equipement name={equipement.name} key={index} image={equipement.image}/>))}
            </div>

            <h4>MR</h4>
            <div className={styles.equipement}>
                {SwordMR.map((equipement, index) => (<Equipement name={equipement.name} key={index} image={equipement.image}/>))}
            </div>
            <h4>SR</h4>
            <div className={styles.equipement}>
                {SwordSR.map((equipement, index) => (<Equipement name={equipement.name} key={index} image={equipement.image}/>))}
            </div>
            <h4>R</h4>
            <div className={styles.equipement}>
                {SwordR.map((equipement, index) => (<Equipement name={equipement.name} key={index} image={equipement.image}/>))}
            </div>
            <h4>N</h4>
            <div className={styles.equipement}>
                {SwordN.map((equipement, index) => (<Equipement name={equipement.name} key={index} image={equipement.image}/>))}
            </div>
            
        </div>
      
      
      <footer className={styles.footer}>

      </footer>
    </div>
  )
}