import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Unite} from '../src/composants/Unite/Unite'
import {Element} from '../src/composants/Unite/Element'
import {Chimere} from '../src/composants/Chimere/Chimere'
import {Header} from '../src/composants/Header/Header'
import {SideBar} from '../src/composants/SideBar/SideBar'
import {AV} from '../src/composants/AV/AV'

export default function Home() {
    var unitesURWater=[{
        name:'Graziella', element:'water', sniv:'/niv:', niv:0, image:'/images/Unite/Graziella.png'},{
        name:'Ildyra', element:'water', sniv:'/niv:', niv:0, image:'/images/Unite/Ildyra.png'},{
        name:'Miranda', element:'water', sniv:'/niv:', niv:0, image:'/images/Unite/Miranda.png'},{
        name:'Moore', element:'water', sniv:'/niv:', niv:0, image:'/images/Unite/Moore.png'},{
        name:'Ramada Hiver', element:'water', sniv:'/niv:', niv:0, image:'/images/Unite/Ramada Hiver.png'},{
        name:'Tidus', element:'water', sniv:'/niv:', niv:0, image:'/images/Unite/Tidus.png'},{
        name:'Vinera Hiver', element:'water', sniv:'/niv:', niv:0, image:'/images/Unite/Vinera Hiver.png'}
        ]
      var unitesMRWater=[{
        name:'Creysse', element:'water', sniv:'/niv:', niv:99, image:'/images/Unite/MR/Creysse.png'},{
        name:'Ramada', element:'water', sniv:'/niv:', niv:0, image:'/images/Unite/MR/Ramada.png'},{
        name:'Tyrrell', element:'water', sniv:'/niv:', niv:120, image:'/images/Unite/MR/Tyrrell.png'}
      ]
      var unitesSRWater=[{
        name:'Sévéro', element:'water', sniv:'/niv:', niv:99, image:'/images/Unite/SR/Sévéro.png'},{
        name:'Yuni', element:'water', sniv:'/niv:', niv:0, image:'/images/Unite/SR/Yuni.png'}
      ]
      var unitesNWater=[{
        name:'Zazan', element:'water', sniv:'/niv:', niv:99, image:'/images/Unite/N/Zazan.png'}
      ]

      var atvURWater=[{
        name:'A cheval sous la neige', elem:'water', image:'/images/AV/A cheval sous la neige.png'},{
        name:'Astrologue extralucide', elem:'water', image:'/images/AV/Astrologue extralucide.png'},{
        name:'Célébration de lhiver', elem:'water', image:'/images/AV/Célébration de lhiver.png'},{
        name:'Léviathan', elem:'water', image:'/images/AV/Léviathan.png'},{
        name:'Merci pour vos votes !', elem:'water', image:'/images/AV/Merci pour vos votes !.png'},{
        name:'Sirène', elem:'water', image:'/images/AV/Sirène.png'},{
        name:'Suteki Da Ne', elem:'water', image:'/images/AV/Suteki Da Ne.png'}
      ]
  
      var atvMRWater=[{
        name:'En quête de myrrhe', elem:'water', image:'/images/AV/MR/En quête de myrrhe.png'},{
        name:'Ensorceleur', elem:'water', image:'/images/AV/MR/Ensorceleur.png'},{
        name:'Tranquillité éphémère', elem:'water', image:'/images/AV/MR/Tranquillité éphémère.png'},{
        name:'Un monde inconnu', elem:'water', image:'/images/AV/MR/Un monde inconnu.png'}
      ]

    var chimereURWater=[{
        name:'Léviathan', elem:'water', image:'/images/Chimère/Léviathan.png'},{
        name:'Sirène', elem:'water', image:'/images/Chimère/Sirène.png'}
        ]

    var chimereMRWater=[{
        name:'Ensorceleur', elem:'water', image:'/images/Chimère/Ensorceleur.png'}
        ]

        
      return (

        <div className={styles.container}>
            <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header/>
            <SideBar/>

            <div className={styles.uniteContainer}>
            <h4>Water UR</h4>
            <Element elem='water' name='water' ></Element>
            <h5>Unités UR</h5>
                
                <div className={styles.elemWaterContainer}>
                {unitesURWater.map((unite, index) => (<Unite name={unite.name} element={unite.element} sniv={unite.sniv} niv={unite.niv} key={index} image={unite.image}/>))}
                </div>
            <h5>Atout vision UR</h5>
                <div className={styles.AV2}>
                    {atvURWater.map((av, index) => (<AV name={av.name} element={av.elem} key={index} image={av.image}/>))}
                </div>
            <h5>Chimère UR</h5>
                <div className={styles.chimere}>
                    {chimereURWater.map((chimere, index) => (<Chimere name={chimere.name} element={chimere.elem} key={index} image={chimere.image}/>))}
                </div>
            <h4>Water MR</h4>
            <h5>Unités MR</h5>
                <div className={styles.elemWaterContainer}>
                {unitesMRWater.map((unite, index) => (<Unite name={unite.name} element={unite.element} sniv={unite.sniv} niv={unite.niv} key={index} image={unite.image}/>))}
                </div>
            <h5>Atout vision MR</h5>
                <div className={styles.AV2}>
                    {atvMRWater.map((av, index) => (<AV name={av.name} element={av.elem} key={index} image={av.image}/>))}
                </div>
            <h5>Chimère MR</h5>
                <div className={styles.chimere}>
                    {chimereMRWater.map((chimere, index) => (<Chimere name={chimere.name} element={chimere.elem} key={index} image={chimere.image}/>))}
                </div>
            <h4>Water SR</h4>
                <div className={styles.elemWaterContainer}>
                {unitesSRWater.map((unite, index) => (<Unite name={unite.name} element={unite.element} sniv={unite.sniv} niv={unite.niv} key={index} image={unite.image}/>))}
                </div>
            <h4>Water N</h4>
            <h5>Unité N</h5>
                <div className={styles.elemWaterContainer}>
                {unitesNWater.map((unite, index) => (<Unite name={unite.name} element={unite.element} sniv={unite.sniv} niv={unite.niv} key={index} image={unite.image}/>))}
                </div>

        </div>
        </div>
    )
}