import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Unite} from '../src/composants/Unite/Unite'
import {Element} from '../src/composants/Unite/Element'
import {Chimere} from '../src/composants/Chimere/Chimere'
import {Header} from '../src/composants/Header/Header'
import {SideBar} from '../src/composants/SideBar/SideBar'
import {AV} from '../src/composants/AV/AV'
import { useState, useEffect } from 'react'
const axios = require('axios');

export default function Home() {
    const [uniteswindUR, setUniteswindUR] = useState([]);
    useEffect(() =>{
        test()
    }, [])

    const [uniteswindMR, setUniteswindMR] = useState([]);
    useEffect(() =>{
        test2()
    }, [])

  // var unitesURWind=[{
  //   name:'2B', element:'wind', sniv:'/niv:', niv:0, image:'/images/Unite/2B.png'},{
  //   name:'Ayaka', element:'wind', sniv:'/niv:', niv:0, image:'/images/Unite/Ayaka.png'},{
  //   name:'Corwell', element:'wind', sniv:'/niv:', niv:0, image:'/images/Unite/Corwell.png'},{
  //   name:'Howlett', element:'wind', sniv:'/niv:', niv:0, image:'/images/Unite/Howlett.png'},{
  //   name:'Lillyla Halloween', element:'wind', sniv:'/niv:', niv:0, image:'/images/Unite/Lillyla Halloween.png'},{
  //   name:'Lucia', element:'wind', sniv:'/niv:', niv:0, image:'/images/Unite/Lucia.png'},{
  //   name:'Oldoa', element:'wind', sniv:'/niv:', niv:0, image:'/images/Unite/Oldoa.png'},{
  //   name:'Yelma', element:'wind', sniv:'/niv:', niv:0, image:'/images/Unite/Yelma.png'}
  // ]
  
  // var unitesMRWind=[{
  //   name:'Cadia', element:'wind', sniv:'/niv:', niv:99, image:'/images/Unite/MR/Cadia.png'},{
  //   name:'Dario Hourne', element:'wind', sniv:'/niv:', niv:0, image:'/images/Unite/MR/Dario Hourne.png'},{
  //   name:'Helena Leonis', element:'wind', sniv:'/niv:', niv:120, image:'/images/Unite/MR/Helena Leonis.png'},{
  //   name:'Loreila', element:'wind', sniv:'/niv:', niv:0, image:'/images/Unite/MR/Loreila.png'}
  // ]

  var unitesSRWind=[{
    name:'Sosha', element:'wind', sniv:'/niv:', niv:99, image:'/images/Unite/SR/Sosha.png'}
  ]

  var unitesRWind=[{
    name:'Mia', element:'wind', sniv:'/niv:', niv:99, image:'/images/Unite/R/Mia.png'}
  ]

  var atvURWind=[{
    name:'Exorciser les démons', elem:'wind', image:'/images/AV/Exorciser les démons.png'},{
    name:'Mobius du désespoir et de la vérité', elem:'wind', image:'/images/AV/Mobius du désespoir et de la vérité.png'},{
    name:'Moment paisible', elem:'wind', image:'/images/AV/Moment paisible.png'},{
    name:'NieR Automata', elem:'wind', image:'/images/AV/NieR Automata.png'},{
    name:'Nouveau sujet de recherche', elem:'wind', image:'/images/AV/Nouveau sujet de recherche.png'},{
    name:'Tétra-Sylphides', elem:'wind', image:'/images/AV/Tétra-Sylphides.png'},{
    name:'Typhon', elem:'wind', image:'/images/AV/Typhon.png'}
  ]

  var atvMRWind=[{
    name:'Chocobo', elem:'wind', image:'/images/AV/MR/Chocobo.png'},{
    name:'Espoirs inutiles', elem:'wind', image:'/images/AV/MR/Espoirs inutiles.png'},{
    name:'Faux-semblant', elem:'wind', image:'/images/AV/MR/Faux-semblant.png'},{
    name:'Morbol', elem:'wind', image:'/images/AV/MR/Morbol.png'}
  ]

      var chimereURWind=[{
        name:'Tétra-Sylphides', elem:'wind', image:'/images/Chimère/Tétra-Sylphides.png'},{
        name:'Typhon', elem:'wind', image:'/images/Chimère/Typhon.png'}
        ]
      
      var chimereMRWind=[{
        name:'Chocobo', elem:'wind', image:'/images/Chimère/Chocobo.png'},{
        name:'Morbol', elem:'wind', image:'/images/Chimère/Morbol.png'}
        ]
        
      var chimereSRWind=[{
        name:'Zu', elem:'wind', image:'/images/Chimère/Zu.png'}
        ]

        const test = async () => {
          let response = await axios.get('http://localhost:8080/api/Unites/wind/UR');
          setUniteswindUR(response.data);
      }
      
      const test2 = async () => {
          let response = await axios.get('http://localhost:8080/api/Unites/wind/MR');
          setUniteswindMR(response.data);
      }

      return (

        <div className={styles.container}>
            <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header/>
            <SideBar/>

            <div className={styles.uniteContainer}>
            <h4>Wind UR</h4>
            <Element elem='wind' name='wind' ></Element>
            <h5>Unités UR</h5>
                
                <div className={styles.elemWindContainer}>
                {uniteswindUR.map((unite, index) => (<Unite name={unite.name} element={unite.element} sniv={unite.sniv} niv={unite.niv} key={index} image={unite.image}/>))}
                </div>
            <h5>Atout vision UR</h5>
                <div className={styles.AV2}>
                    {atvURWind.map((av, index) => (<AV name={av.name} element={av.elem} key={index} image={av.image}/>))}
                </div>
            <h5>Chimère UR</h5>
                <div className={styles.chimere}>
                    {chimereURWind.map((chimere, index) => (<Chimere name={chimere.name} element={chimere.elem} key={index} image={chimere.image}/>))}
                </div>
            <h4>Wind MR</h4>
            <h5>Unités MR</h5>
                <div className={styles.elemWindContainer}>
                {uniteswindMR.map((unite, index) => (<Unite name={unite.name} element={unite.element} sniv={unite.sniv} niv={unite.niv} key={index} image={unite.image}/>))}
                </div>
            <h5>Atout vision MR</h5>
                <div className={styles.AV2}>
                    {atvMRWind.map((av, index) => (<AV name={av.name} element={av.elem} key={index} image={av.image}/>))}
                </div>
            <h5>Chimère MR</h5>
                <div className={styles.chimere}>
                    {chimereMRWind.map((chimere, index) => (<Chimere name={chimere.name} element={chimere.elem} key={index} image={chimere.image}/>))}
                </div>
            <h4>Wind SR</h4>
                <div className={styles.elemWindContainer}>
                {unitesSRWind.map((unite, index) => (<Unite name={unite.name} element={unite.element} sniv={unite.sniv} niv={unite.niv} key={index} image={unite.image}/>))}
                </div>
                <div className={styles.chimere}>
                    {chimereSRWind.map((chimere, index) => (<Chimere name={chimere.name} element={chimere.elem} key={index} image={chimere.image}/>))}
                </div>
            <h4>Wind R</h4>
                <div className={styles.elemWindContainer}>
                {unitesRWind.map((unite, index) => (<Unite name={unite.name} element={unite.element} sniv={unite.sniv} niv={unite.niv} key={index} image={unite.image}/>))}
                </div>
          </div>

        </div>
    )
}